In [1]:
from sortasurvey.notebook import Survey, rank
from sortasurvey.sample import Sample

### The `Sample` class

#### Functionality within the target selection process:

But first, because it's easy and we already have all the required info, let's create the `Survey` first.

In [2]:
TKS = Survey(path_sample='info/TKS_sample.csv', path_survey='info/survey_info.csv', \
             path_priority='info/high_priority.csv', path_ignore='info/no_no.csv')

Initialization of a `Sample` requires one positional argument, the survey `program` of interest, and also has three optional, keyword arguments (`survey`=`None`, `path_init`=`info/TKS_sample.csv`, `path_final`=`None`). The main use of the `Sample` during the target selection process is directly after a program is selected. An instance of the `Sample` class is created at every iteration, which filters the most up-to-date, full survey sample (e.g., `info/TKS_sample.csv`) to address the requirements/needs for the specified `program`. If the survey is not `None`, the programs and sample attributes of the provided survey are copied and stored as attributes to the `Sample` class object. Finally, the method `Sample.get_vetted_science` is called and creates the filtered sample (as described above).

BLAH BLAH BLAH BLAH (I know)... you are probably asking why you should care? In short, it's because there are some neat, quick tricks to take the full sample and transform it to a possible sample of interest. For example, we can do what we just explained in a one-liner.

In [3]:
program='SC2C'      # TKS multis

sample = Sample(program, survey=TKS)
sample.query[['toi','tic','disp','ra','dec','vmag','evol','r_s','t_eff','rp','period','sinc']]

toi        tic  disp        ra      dec    vmag evol   r_s   t_eff  \
0   1136.01  142276270   CPC  192.1849  64.8553   9.534   MS  0.98  5767.0   
1   1246.01  230127302    PC  251.1165  70.4296  11.632   MS  0.88  5141.0   
2   1339.01  269701147   CPC  302.0240  66.8506   8.970   MS  0.92  5461.0   
3    561.01  377064495   VPC  148.1856   6.2164  10.252   MS  0.84  5440.0   
4   1812.02  207425167    PC  242.7477  58.2946  12.431   MS  0.74  5059.0   
5   1726.01  130181866     P  117.4794  27.3632   6.920   MS  0.90  5694.0   
6    266.01  164767175    PC   26.2096 -18.4009  10.070   MS  0.92  5784.0   
7   2076.01   27491137    PC  217.3927  39.7904   9.139   MS  0.77  5163.0   
8    261.02   63898957    PC   15.2176 -24.4239   9.560   MS  1.28  5890.0   
9   1670.02  441739020    PC  259.0173  72.1612   9.889   MS  1.31  6345.0   
10  1347.01  229747848   PPC  280.3268  70.2899  11.168   MS  0.85  5424.0   
11  1438.01  229650439    PC  280.9243  74.9376  10.957   MS  0.82  5259.0   
12  1453.01  198390247  VPC-  258.2238  57.1978  11.113   MS  0.71  4920.0   
13  1798.01  198153540    PC  211.0941  46.5194  11.361   MS  0.78  5165.0   
14  1269.01  198241702    PC  249.6971  64.5587  11.618   MS  0.85  5517.0   
15  1346.01  219852882    PC  256.6229  68.8429  11.693   MS  0.78  4965.0   
16  1803.01  144401492    PC  178.0466  35.1718  11.871   MS  0.69  4868.0   
17  1260.01  355867695   VPC  157.1459  65.8546  11.922   MS  0.69  4225.0   
18  1468.01  243185500   VPC   16.6541  19.2259  12.500   MS  0.37  3382.0   
19   736.01  181804752   VPC  165.6915 -16.4062  16.910   MS  0.17  2949.0   
20  1266.01  467179528   VPC  197.9982  65.8338  12.941   MS  0.44  3618.0   
21  1730.01  318022259    PC  107.8664  48.3304  12.230   MS  0.53  3691.0   
22  1782.01  160045097   CPC  213.0800  74.4116  12.329   MS  0.67  4336.0   

      rp     period    sinc  
0   4.72  12.517810    77.0  
1   3.33  18.652357    27.0  
2   3.20   8.880406    99.0  
3   3.77  10.781327    66.0  
4   3.08  11.614081    35.0  
5   2.16   7.108153   145.0  
6   2.41  10.767807   104.0  
7   2.89  10.355753    48.0  
8   3.35  13.039359   243.0  
9   2.14  10.983868   229.0  
10  2.06   0.847366  1876.0  
11  2.81   5.140020    12.0  
12  2.25   6.588680    51.0  
13  2.39   8.018944    69.0  
14  2.38   4.252932   231.0  
15  2.10   5.502610   130.0  
16  4.03  12.891153    24.0  
17  2.40   3.127160   103.0  
18  2.33  15.531925     2.0  
19  2.02   4.990070     1.0  
20  2.41  10.895412     5.0  
21  2.30   6.222236    16.0  
22  2.56   4.987638    56.0

Remember that the only requirement for the TKS multis program is more than one planet. Now if you look at the above list of TOIs, you may notice that there is only one entry (or TIC) per TOI. This is because the initialization calls `sample.get_vetted_science()`, which has a default keyword argument `drop_dup` set to `True`. For purposes of target selection, this is helpful to avoid double selections (when in reality, you are only observing the one star).

So let's turn that off.

In [4]:
sample.get_vetted_science(drop_dup=False)
sample.query[['toi','tic','disp','ra','dec','vmag','evol','r_s','t_eff','rp','period','sinc']]

toi        tic   disp        ra      dec    vmag evol   r_s   t_eff  \
0   1136.01  142276270    CPC  192.1849  64.8553   9.534   MS  0.98  5767.0   
1   1136.02  142276270    CPC  192.1849  64.8553   9.534   MS  0.98  5767.0   
2   1136.03  142276270     PC  192.1849  64.8553   9.534   MS  0.98  5767.0   
3   1136.04  142276270     PC  192.1849  64.8553   9.534   MS  0.98  5767.0   
4   1246.01  230127302     PC  251.1165  70.4296  11.632   MS  0.88  5141.0   
5   1246.02  230127302   VPC-  251.1165  70.4296  11.632   MS  0.88  5141.0   
6   1246.03  230127302     PC  251.1165  70.4296  11.632   MS  0.88  5141.0   
7   1246.04  230127302     PC  251.1165  70.4296  11.632   MS  0.88  5141.0   
8   1339.01  269701147    CPC  302.0240  66.8506   8.970   MS  0.92  5461.0   
9   1339.02  269701147     PC  302.0240  66.8506   8.970   MS  0.92  5461.0   
10  1339.03  269701147     PC  302.0240  66.8506   8.970   MS  0.92  5461.0   
11   561.01  377064495    VPC  148.1856   6.2164  10.252   MS  0.84  5440.0   
12   561.02  377064495    CPC  148.1856   6.2164  10.252   MS  0.84  5440.0   
13   561.03  377064495     PC  148.1856   6.2164  10.252   MS  0.84  5440.0   
14  1812.02  207425167     PC  242.7477  58.2946  12.431   MS  0.74  5059.0   
15  1812.03  207425167     PC  242.7477  58.2946  12.431   MS  0.74  5059.0   
16  1726.01  130181866      P  117.4794  27.3632   6.920   MS  0.90  5694.0   
17  1726.02  130181866      P  117.4794  27.3632   6.920   MS  0.90  5694.0   
18   266.01  164767175     PC   26.2096 -18.4009  10.070   MS  0.92  5784.0   
19   266.02  164767175   STPC   26.2096 -18.4009  10.070   MS  0.92  5784.0   
20  2076.01   27491137     PC  217.3927  39.7904   9.139   MS  0.77  5163.0   
21  2076.02   27491137     PC  217.3927  39.7904   9.139   MS  0.77  5163.0   
22   261.02   63898957     PC   15.2176 -24.4239   9.560   MS  1.28  5890.0   
23  1670.02  441739020     PC  259.0173  72.1612   9.889   MS  1.31  6345.0   
24  1347.01  229747848    PPC  280.3268  70.2899  11.168   MS  0.85  5424.0   
25  1347.02  229747848     PC  280.3268  70.2899  11.168   MS  0.85  5424.0   
26  1438.01  229650439     PC  280.9243  74.9376  10.957   MS  0.82  5259.0   
27  1438.02  229650439     PC  280.9243  74.9376  10.957   MS  0.82  5259.0   
28  1453.01  198390247   VPC-  258.2238  57.1978  11.113   MS  0.71  4920.0   
29  1453.02  198390247     PC  258.2238  57.1978  11.113   MS  0.71  4920.0   
30  1798.01  198153540     PC  211.0941  46.5194  11.361   MS  0.78  5165.0   
31  1798.02  198153540     PC  211.0941  46.5194  11.361   MS  0.78  5165.0   
32  1269.01  198241702     PC  249.6971  64.5587  11.618   MS  0.85  5517.0   
33  1269.02  198241702     PC  249.6971  64.5587  11.618   MS  0.85  5517.0   
34  1346.01  219852882     PC  256.6229  68.8429  11.693   MS  0.78  4965.0   
35  1346.02  219852882     PC  256.6229  68.8429  11.693   MS  0.78  4965.0   
36  1803.01  144401492     PC  178.0466  35.1718  11.871   MS  0.69  4868.0   
37  1803.02  144401492    VPC  178.0466  35.1718  11.871   MS  0.69  4868.0   
38  1260.01  355867695    VPC  157.1459  65.8546  11.922   MS  0.69  4225.0   
39  1260.02  355867695    CPC  157.1459  65.8546  11.922   MS  0.69  4225.0   
40  1468.01  243185500    VPC   16.6541  19.2259  12.500   MS  0.37  3382.0   
41  1468.02  243185500  VPC+?   16.6541  19.2259  12.500   MS  0.37  3382.0   
42   736.01  181804752    VPC  165.6915 -16.4062  16.910   MS  0.17  2949.0   
43   736.02  181804752    VPC  165.6915 -16.4062  16.910   MS  0.17  2949.0   
44  1266.01  467179528    VPC  197.9982  65.8338  12.941   MS  0.44  3618.0   
45  1266.02  467179528    VPC  197.9982  65.8338  12.941   MS  0.44  3618.0   
46  1730.01  318022259     PC  107.8664  48.3304  12.230   MS  0.53  3691.0   
47  1730.02  318022259    PPC  107.8664  48.3304  12.230   MS  0.53  3691.0   
48  1782.01  160045097    CPC  213.0800  74.4116  12.329   MS  0.67  4336.0   
49  1782.02  160045097     PC  213.0800  74.4116  12.329  

Now you can see that the number of rows more than doubled, which is a good sanity check for planet multiplicity! You might also notice that the sample is already prioritized, where systems with the highest planet multiplicity are up at the top. TOIs 1136 and 1246 both have 4 planet candidates, but 1136 is ranked first, hmm. SC2C sorts by planet multiplicity and then by the "actual_cost" of the target, where cheaper targets are ranked more highly. Here the selection process isn't relevant, but fortunately it still calculates the cost (i.e. exposure time) of targets and  should only depend on the magnitude (and possibly existing observations) in this case.

In [5]:
# TOI 1136
index = sample.query.index[sample.query['toi'] == 1136.03].tolist()[0]
cost = sample.query.loc[index,'actual_cost']         # exposure times are calculated in seconds
print('The cost for TOI 1136 is %.2f hours'%(cost/60./60.))

The cost for TOI 1136 is 5.48 hours


In [6]:
# TOI 1246
index = sample.query.index[sample.query['toi'] == 1246.02].tolist()[0]
cost = sample.query.loc[index,'actual_cost']
print('The cost for TOI 1246 is %.2f hours'%(cost/60./60.))

The cost for TOI 1246 is 22.03 hours


As you can see, currently TOI 1246 would require ~4x the amount of telescope time to acquire the program's goals ($nobs=100$) and therefore ranked the correct target first! In the target selection iterations, the built-in method `get_highest_priority` is called, which returns the highest ranked star for that program that has not yet been selected by the program. Here, it should return the first...

In [7]:
pick = sample.get_highest_priority()
print(pick.toi)

1136.01


Yay!

#### Functionality outside the target selection process: